---
title: "Reproducibility Report for Individual Differences in the Association Between Subjective Stress and Heart Rate Are Related to Psychological and Physical Well-Being by Sommerfeldt et al., (2019, Psychological Science)"
author: "Kris Evans"
      "Reproducibility Project Author[s] (sasha.sommerfeldt@wisc.edu)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
---

## Introduction

This study aimed to establish and validate the value of a particular construct described as coherence. Coherence is a measure of accordance between self-reported stress and heart rate. Evidence suggests coherence is associated with healthy mind-body functioning and adaptivity. The authors hypothesize that the within-participants association between self-reported stress and heart rate is positively related to psychological and physical well-being and negatively related to denial coping. 

I chose to reproduce the analyses for this study due to the rich, multi-modal, and dimensional data available and my interest in adding the methods to my toolkit. I'm particularly interested in interventions that use this measure as a means of enhancement of meta-awareness, health, and well-being.


**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

Using linear mixed-effects models, I will use the coherence model below to investigate the relationship of coherence with measures of health and well-being. Fundamental analyses include replicating the stress-heart rate model to predict well-being across various measures (psychological well-being, depression, anxiety, interleukin-6, and denial coping).

I will focus on the interaction effect in this model, representing the degree to which within-participants associations between self-reported stress and heart rate are related to the well-being indicator (PWB, depression, anxiety, IL-6, and CRP) or denial coping.

lmer(heartRate stressClusterMeanCentered ∼ * wellbeingCentered + StressClusterMeanCentered * ageCentered(1 + stressClusterMeanCentered | subject) + (1 + d | subject) + () = 1 | family data dfLong )

### Justification for choice of study

I chose to reproduce this study for three main reasons. One is because I get to use a rich and robust data set that would be impossible to replicate due to the expansive and longitudinal nature. Additionally, this data set's multi-modal nature may stimulate future inquiry and publication that spans across domains. The second and third reason is my interest in gaining a better grasp and practice using the statistical and operational methods in this study for possible future use or exploratory analyses.

### Anticipated challenges

I foresee some challenges related to data analysis and interpretation based on adequate cleaning and wrangling. I do have access to the raw and processed data, which should reduce that challenge, but because this requires cleaning, tidying, and transforming many different variables, it introduces chances of error. It may be challenging to understand and justify the methods of the models fully.

### Links

Project repository (https://github.com/cardinal24/writeup.git): 

Original paper (https://github.com/cardinal24/sommerfeldt2019.git): 

## Methods
"Participants completed a standardized laboratory-based experimental stress-induction paradigm designed to measure cardiovascular reactivity and recovery from stress (Crowley et al., 2011) detailed documentation of the study protocol is publicly available at http://www.midus.wisc.edu/midus2/project4/). The data were collected at the University of California, Los Angeles; Georgetown University; and the University of Wisconsin and processed at the Columbia University Medical Center in the laboratory of Richard Sloan.

The stress-induction paradigm involved a resting baseline (11 min); two cognitive-psychological stressor tasks (6 min each; counterbalanced across participants); a seated, resting period after each task (recovery period; 6 min each); and an orthostatic challenge, which involved moving from a seated to a standing position and remaining standing (6 min). The orthostatic phase of the task was not included in the analyses because changes in heart rate during this phase are confounded with physical movement. Thus, we examined five phases of interest: baseline, first stressor task, first recovery, second stressor task, and second recovery.

Participants’ heart rate was measured using electrocardiograph electrodes placed on the left and right shoulders and in the left lower quadrant. Heart rate was measured continuously over every phase of the task. Heart rate was calculated as an average of all valid interbeat intervals and converted from interbeat-interval units (milliseconds) to beats-per-minute units. The average of a 5-min epoch was analyzed for each of the five phases of the task. Each epoch was scored for quality, and only epochs containing a full 5 min of good signal quality, without any designated invalid intervals of data that had to be omitted, were included in the analysis. We chose to examine the average heart rate for each phase of the task because the precise timing of each subjective report was not recorded on the physiological time series, and subjective reports did not necessarily occur during the peak physiological response. 

Participants were informed at the beginning of the session that, periodically, they would be asked for a verbal stress rating on a scale from 1 (not stressed at all) to 10 (extremely stressed). The experimenter prompted each participant to verbally report his or her level of stress approximately 20 to 30 s before the end of each phase of the task. Thus, a total of six self-reports of stress were collected during the session, near the end of each phase: baseline, during each stressor task, during the recovery period following each stressor task, and after the orthostatic challenge. The first five self-reports of stress were used, excluding the ortho-static time point.".

One can estimate a linear mixed-effects model (LMEM) to examine whether the (statistical) effect of one of the Level 1 variables (e.g., subjective stress) on the other Level 1 variable (e.g., heart rate) is moderated by the individual-differences variable. If, for example, the effect of subjective stress on heart rate is stronger for participants high in psychological well-being, then

Age was included as a covariate because of the broad age range of the sample, extending from early to late adulthood and because older participants had lower stress–heart rate coherence, b = −0.008, F(1, 843.0) = 7.754, p = .005. Gender was not associated with stress–heart rate coherence, b = 0.051, F(1, 850.0) = 0.560, p = .455, and so was not included as a covariate in the analyses. We fitted a separate model for each of the five well-being indicators of interest and denial coping (six total tests). The Anova() function in the car package (Version 3.0.0; Fox & Weisberg, 2011) provided esti- mates of F, error df (via Kenward-Roger approximation), and p. Multiple comparisons of the six different tests were corrected using the Holm-Bonferroni method the within-participants association is positively related to psychological well-being

Stroop color-word task. Participants completed a mod- i fied Stroop color-word task (Stroop, 1935). One of four color-name words was presented in a font color that was either congruent or incongruent with the word itself. The colored color-name stimulus appeared on screen, and participants pressed one of four keys on a keypad cor- responding to the color of the letters in the word, not the color name. The rate of stimuli was modified according to participant performance to roughly standardize the degree of stressfulness. This standardization was set so that

For the LMEM approach, I will regress heart rate on self-reported stress (centered around each participant’s own mean), the well-being indicator under consideration (mean centered; e.g., PWB), and their interaction, adjusting for age, the interaction between self-reported stress and age, and nonindependence due to participants and families (Brauer & Curtin, 2018). Our model thus includes six fixed effects: self-reported stress (Level 1), the well-being indicator of interest (Level 2), their interaction, age (Level 2), the interaction of self- reported stress and age, and the intercept. The model includes a by-participant random intercept, a by-participant random slope for stress, and a by-family random intercept. The two by-participant random effects were allowed to correlate.

This model was represented in R as follows:
lmer(heartRate stressClusterMeanCentered ∼ * wellbeingCentered + StressClusterMeanCentered * ageCentered(1 + stressClusterMeanCentered | subject) + (1 + d | subject) + () = 1 | family data dfLong )

Denial coping is at the between participant level
 

### Description of the steps required to reproduce the results

Retrieve, clean, analyze, interpret, and visualize key data, models and tables.

### Differences from original study


## Results

The statistical effect of stress on heart rate was found to be moderated by PWB, b = 0.050, F(1, 822.8) = 26.70, p < .0001; participants with higher stress–heart rate coherence also reported higher psychological well- being. The opposite was true for depressive symptoms, b = −0.249, F(1, 783.7) = 36.77, p < .0001, and trait anxiety, b = −0.211, F(1, 769.4) = 32.49, p < .0001; indi- viduals with higher stress–heart rate coherence reported fewer depressive symptoms and had lower trait anxiety. 

For physical well- being, the statistical effect of stress on heart rate was found to be significantly moderated by IL-6 and CRP; participants with higher stress–heart rate coherence also had lower IL-6, b = −0.145, F(1, 762.3) = 22.20, p < .0001, and lower CRP, b = −0.175, F(1, 827.2) = 7.16, p = .008.

I also investigated whether stress–heart rate coherence was associated with use of denial as a coping strategy.The statistical effect of stress on heart rate was found to be moderated by denial; higher stress–heart rate coherence was associated with less tendency toward the use of denial as a coping strategy, b = −0.069, F(1, 853.3) = 20.69, p < .0001

Reproduction results - N/A

### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Key analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

###Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Reproduction Attempt

Open the discussion section with a paragraph summarizing the primary result from the key analysis and assess whether you successfully reproduced it, partially reproduced it, or failed to reproduce it.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis of the dataset, (b) assessment of the meaning of the successful or unsuccessful reproducibility attempt - e.g., for a failure to reproduce the original findings, are the differences between original and present analyses ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the reproducibility attempt (if you contacted them).  None of these need to be long.
